/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stokprogrami;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableColumn;

/**
 *
 * 
 */
public class Depo extends javax.swing.JFrame {

    //LİSTELE
        public void Listele(){         
          ((DefaultTableModel)tableListe.getModel()).setNumRows(0);
        try{
        Baglanti bgln = new Baglanti();
        bgln.baglan();
        Statement stmt = null;
        ResultSet rs = null;
        Connection conn = bgln.conn;
        stmt = conn.createStatement();

            rs = stmt.executeQuery("Select * from depo");
            int sutunSayisi = rs.getMetaData().getColumnCount();
            rs = stmt.getResultSet();
            
          DefaultTableModel table = (DefaultTableModel)this.tableListe.getModel();
          TableColumnModel sutunBoy = tableListe.getColumnModel();
          
          sutunBoy.getColumn(0).setPreferredWidth(5);
          sutunBoy.getColumn(1).setPreferredWidth(140);
  
            
            while(rs.next()){
 
                Object[] row=new Object[sutunSayisi];
               for(int i=1;i<=sutunSayisi;i++){
                    row[i-1]=rs.getObject(i);
               }
              table.addRow(row);   
            }
            tableListe.setModel(table);
        } catch (SQLException ex) {
            Logger.getLogger(Giris.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
        
       // SİLME
        
        public void Silme(int silinecek){
            
                try{
        Baglanti bgln = new Baglanti();
        bgln.baglan();
        Statement stmt = null;
        Connection conn = bgln.conn;
        stmt = conn.createStatement();
        System.out.println(silinecek);
        
        int yesOrNo = JOptionPane.showConfirmDialog(null, silinecek+" Numaralı Depoyu Silmek İstiyor musunuz ? ","Silme Onay ?", JOptionPane.YES_NO_OPTION);
   
        if(yesOrNo == JOptionPane.YES_OPTION){
                   
        stmt.executeUpdate("Delete From depo where id='"+silinecek+"'");
        JOptionPane.showMessageDialog(null, silinecek+" Numaralı Depo Silinmiştir","Ürün Silme Başarılır",JOptionPane.INFORMATION_MESSAGE);
        Listele();
            
        }else{
            remove(yesOrNo);
        }
                
 
           
            
        } catch (SQLException ex) {
            Logger.getLogger(Giris.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
    public Depo() {
        initComponents();
       
        
       Listele();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDepoEkle = new javax.swing.JButton();
        btnDepoDuzenle = new javax.swing.JButton();
        btnDepoSil = new javax.swing.JButton();
        btnKapat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListe = new javax.swing.JTable();
        lblKim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Depo | Stok Otomasyonu ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnDepoEkle.setText("Depo Ekle");
        btnDepoEkle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDepoEkleMouseClicked(evt);
            }
        });

        btnDepoDuzenle.setText("Depo Düzenle");
        btnDepoDuzenle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDepoDuzenleMouseClicked(evt);
            }
        });

        btnDepoSil.setText("Depo Sil");
        btnDepoSil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDepoSilMouseClicked(evt);
            }
        });

        btnKapat.setText("Kapat");
        btnKapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKapatMouseClicked(evt);
            }
        });

        tableListe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "DEPO ADI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableListe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableListe.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        tableListe.setRowHeight(30);
        tableListe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableListe);

        lblKim.setForeground(new java.awt.Color(255, 255, 255));
        lblKim.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDepoSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDepoDuzenle, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(btnDepoEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKapat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblKim)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDepoEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDepoDuzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDepoSil, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKapat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(lblKim))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableListeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListeMouseClicked
            if(evt.getClickCount()==2){
                btnDepoDuzenleMouseClicked(evt);
            }
    }//GEN-LAST:event_tableListeMouseClicked

    private void btnDepoEkleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepoEkleMouseClicked
       // ÜRÜN EKLE
        
     //StokEkle stkEkle = new StokEkle();
    // new StokEkle(this).setVisible(true);
    DepoEkle dpoEkle = new DepoEkle(this);
    dpoEkle.setVisible(true);
    dpoEkle.setLocationRelativeTo(null);
    
     
    
    }//GEN-LAST:event_btnDepoEkleMouseClicked

    private void btnKapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKapatMouseClicked
        setVisible(false);
        Menu mnu = new Menu();
        mnu.lblKim.setText(lblKim.getText());
        mnu.setVisible(true);
        mnu.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnKapatMouseClicked

    private void btnDepoSilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepoSilMouseClicked
  Yetkilendirme yt = new Yetkilendirme();
        yt.yetkilendirme(lblKim.getText());

        System.out.println(yt.yetki);
        if(yt.yetki.equals("Admin") || yt.yetki.equals("Silme") || yt.yetki.equals("Yönetim Yok")){
             try {
              String deger = tableListe.getValueAt(tableListe.getSelectedRow(), 0).toString();
                System.out.println(deger);
                Silme(Integer.decode(deger));
        } catch (Exception e) {
              JOptionPane.showMessageDialog(null,"Depo Seçmediniz..", "Hata!",JOptionPane.ERROR_MESSAGE);
        }
        }else{
            JOptionPane.showMessageDialog(null, "İznin Yok","Kısıtlama..",JOptionPane.WARNING_MESSAGE);
        }
      
       
      
         
    }//GEN-LAST:event_btnDepoSilMouseClicked

    private void btnDepoDuzenleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepoDuzenleMouseClicked
       // URUN DUZENLE
         Yetkilendirme yt = new Yetkilendirme();
        yt.yetkilendirme(lblKim.getText());

        System.out.println(yt.yetki);
        if(yt.yetki.equals("Admin") || yt.yetki.equals("Düzenleme") || yt.yetki.equals("Yönetim Yok")){
              try {
             String depo_id = tableListe.getValueAt(tableListe.getSelectedRow(), 0).toString();
              String depo_ismi = tableListe.getValueAt(tableListe.getSelectedRow(), 1).toString();
  
              DepoDuzenle dpoDuzenle = new DepoDuzenle(this);
              dpoDuzenle.veriAl(depo_ismi,Integer.parseInt(depo_id));
              dpoDuzenle.setVisible(true);
              dpoDuzenle.setLocationRelativeTo(null);   
              
                
        } catch (Exception e) {
              JOptionPane.showMessageDialog(null,"Depo Seçmediniz..", "Hata!",JOptionPane.ERROR_MESSAGE);
              System.err.println("Hata : " + e);
        }
        }else{
            JOptionPane.showMessageDialog(null, "İznin Yok","Kısıtlama..",JOptionPane.WARNING_MESSAGE);
        }
       
      
       
    
    }//GEN-LAST:event_btnDepoDuzenleMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Menu mnu = new Menu();
        mnu.lblKim.setText(lblKim.getText());
        mnu.setVisible(true);
        mnu.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Depo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Depo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Depo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Depo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
   
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new Depo().setVisible(true);
                   
            }
           
        });
        
  
        
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepoDuzenle;
    private javax.swing.JButton btnDepoEkle;
    private javax.swing.JButton btnDepoSil;
    private javax.swing.JButton btnKapat;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblKim;
    private javax.swing.JTable tableListe;
    // End of variables declaration//GEN-END:variables

  
}
