/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stokprogrami;

import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class Menu extends javax.swing.JFrame {

   

    /**
     * Creates new form Menu
     */
    
     
    
    public Menu() {
        initComponents();
         
         
    }

      
  
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnYonetim = new javax.swing.JButton();
        btnStok = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnDepo = new javax.swing.JButton();
        btnCikis = new javax.swing.JButton();
        lblDepo = new javax.swing.JLabel();
        lblKim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menü | Stok Otomasyonu");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(48, 66, 105));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hastene Stok Otomasyonu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnYonetim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnYonetim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        btnYonetim.setText("YÖNETİM");
        btnYonetim.setFocusable(false);
        btnYonetim.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnYonetim.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnYonetim.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnYonetim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnYonetimMouseClicked(evt);
            }
        });

        btnStok.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stok.png"))); // NOI18N
        btnStok.setText("STOK");
        btnStok.setToolTipText("");
        btnStok.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnStok.setFocusable(false);
        btnStok.setHideActionText(true);
        btnStok.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStok.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnStok.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStokMouseClicked(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        btnCari.setText("CARİ");
        btnCari.setFocusable(false);
        btnCari.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCari.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCari.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCariMouseClicked(evt);
            }
        });

        btnDepo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDepo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/depo.png"))); // NOI18N
        btnDepo.setText("DEPO");
        btnDepo.setFocusable(false);
        btnDepo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDepo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnDepo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDepo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDepoMouseClicked(evt);
            }
        });

        btnCikis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kapat.png"))); // NOI18N
        btnCikis.setText("ÇIKIŞ");
        btnCikis.setFocusable(false);
        btnCikis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCikis.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCikis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCikisMouseClicked(evt);
            }
        });

        lblKim.setForeground(new java.awt.Color(255, 255, 255));
        lblKim.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnStok, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnYonetim, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKim)
                        .addGap(66, 66, 66)
                        .addComponent(btnDepo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCikis, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDepo)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnYonetim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCikis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblKim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lblDepo))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// ÇIKIŞ BUTONU
    private void btnCikisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCikisMouseClicked
        System.exit(0);
                
    }//GEN-LAST:event_btnCikisMouseClicked

    
    // STOK BUTONU
    private void btnStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStokMouseClicked
        // TODO add your handling code here:
       
        setVisible(false);
        Stok stk = new Stok();
        stk.lblKim.setText(lblKim.getText());
        stk.setVisible(true);
        
        stk.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnStokMouseClicked

    private void btnDepoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepoMouseClicked
        setVisible(false);
        Depo dpo = new Depo();
        dpo.lblKim.setText(lblKim.getText());
        dpo.setVisible(true);
        dpo.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnDepoMouseClicked

    private void btnYonetimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYonetimMouseClicked
        Yetkilendirme yt = new Yetkilendirme();
        
        yt.yetkilendirme(lblKim.getText());
        System.out.println(yt.yetki);
        if(yt.yetki.equals("Admin")){
             setVisible(false);
        Yonetim yntm = new Yonetim();
        yntm.lblKim.setText(lblKim.getText());
        yntm.setVisible(true);
        yntm.setLocationRelativeTo(null);
        }else{
             JOptionPane.showMessageDialog(null, "İznin Yok","Kısıtlama..",JOptionPane.WARNING_MESSAGE);
        }


       
    }//GEN-LAST:event_btnYonetimMouseClicked

    private void btnCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariMouseClicked
        setVisible(false);
        Cari cri = new Cari();
        cri.setVisible(true);
        cri.lblKim.setText(lblKim.getText());
        cri.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCariMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCikis;
    private javax.swing.JButton btnDepo;
    private javax.swing.JButton btnStok;
    private javax.swing.JButton btnYonetim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDepo;
    public javax.swing.JLabel lblKim;
    // End of variables declaration//GEN-END:variables
}
