/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stokprogrami;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableColumn;

/**
 *
 * 
 */
public class Yonetim extends javax.swing.JFrame {

    //LİSTELE
        public void Listele(){         
          ((DefaultTableModel)tableListe.getModel()).setNumRows(0);
        try{
        Baglanti bgln = new Baglanti();
        bgln.baglan();
        Statement stmt = null;
        ResultSet rs = null;
        Connection conn = bgln.conn;
        stmt = conn.createStatement();

            rs = stmt.executeQuery("Select * from kullanici");
            int sutunSayisi = rs.getMetaData().getColumnCount();
            rs = stmt.getResultSet();
            
          DefaultTableModel table = (DefaultTableModel)this.tableListe.getModel();
          TableColumnModel sutunBoy = tableListe.getColumnModel();
          
          sutunBoy.getColumn(0).setPreferredWidth(5);
          sutunBoy.getColumn(1).setPreferredWidth(75);
          sutunBoy.getColumn(2).setPreferredWidth(75);
          sutunBoy.getColumn(3).setPreferredWidth(15);
          sutunBoy.getColumn(4).setPreferredWidth(40);
          sutunBoy.getColumn(5).setPreferredWidth(15);
         
            
            while(rs.next()){
 
                Object[] row=new Object[sutunSayisi];
               for(int i=1;i<=sutunSayisi;i++){
                    row[i-1]=rs.getObject(i);
               }
              table.addRow(row);   
            }
            tableListe.setModel(table);
        } catch (SQLException ex) {
            Logger.getLogger(Giris.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
        
       // SİLME
        
        public void Silme(int silinecek){
                
            System.out.println(tableListe.getValueAt(tableListe.getSelectedRow(), 0).toString());
            
                try{
        Baglanti bgln = new Baglanti();
        bgln.baglan();
        Statement stmt = null;
        Connection conn = bgln.conn;
        stmt = conn.createStatement();
        System.out.println(silinecek);
        
        int yesOrNo = JOptionPane.showConfirmDialog(null, silinecek+" Numaralı Kullanıcı Silmek İstiyor musunuz ? ","Silme Onay ?", JOptionPane.YES_NO_OPTION);
   
        if(yesOrNo == JOptionPane.YES_OPTION){
                   
        stmt.executeUpdate("Delete From kullanici where id='"+silinecek+"'");
        JOptionPane.showMessageDialog(null, silinecek+" Numaralı Kullanıcı Silinmiştir","Ürün Silme Başarılır",JOptionPane.INFORMATION_MESSAGE);
        Listele();
            
        } 
                
 
           
            
        } catch (SQLException ex) {
                    System.err.println(ex);
        }
            
        }
    public Yonetim() {
        initComponents();
       
        
       Listele();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKullaniciEkle = new javax.swing.JButton();
        btnKullaniciDuzenle = new javax.swing.JButton();
        btnKullaniciSil = new javax.swing.JButton();
        btnKapat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListe = new javax.swing.JTable();
        lblKim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Yönetim | Stok Otomasyonu ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnKullaniciEkle.setText("Kullanıcı Ekle");
        btnKullaniciEkle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKullaniciEkleMouseClicked(evt);
            }
        });

        btnKullaniciDuzenle.setText("Kullanıcı  Düzenle");
        btnKullaniciDuzenle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKullaniciDuzenleMouseClicked(evt);
            }
        });

        btnKullaniciSil.setText("Kullanıcı Sil");
        btnKullaniciSil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKullaniciSilMouseClicked(evt);
            }
        });

        btnKapat.setText("Kapat");
        btnKapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKapatMouseClicked(evt);
            }
        });

        tableListe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "KULLANICI ADI", "ŞİFRE", "SİLME", "DÜZENLEME", "ADMİN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableListe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableListe.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        tableListe.setRowHeight(30);
        tableListe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableListe);

        lblKim.setForeground(new java.awt.Color(255, 255, 255));
        lblKim.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnKullaniciSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKullaniciDuzenle, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(btnKullaniciEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKapat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblKim))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKullaniciEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKullaniciDuzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKullaniciSil, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKapat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblKim))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableListeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListeMouseClicked
            if(evt.getClickCount()==2){
                btnKullaniciDuzenleMouseClicked(evt);
            }
    }//GEN-LAST:event_tableListeMouseClicked

    private void btnKullaniciEkleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKullaniciEkleMouseClicked
       // ÜRÜN EKLE
        
     //StokEkle stkEkle = new StokEkle();
    // new StokEkle(this).setVisible(true);
    YonetimEkle yntmEkle = new YonetimEkle(this);
    yntmEkle.setVisible(true);
    yntmEkle.setLocationRelativeTo(null);
    
     
    
    }//GEN-LAST:event_btnKullaniciEkleMouseClicked

    private void btnKapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKapatMouseClicked
        setVisible(false);
        Menu mnu = new Menu();
        mnu.lblKim.setText(lblKim.getText());
        mnu.setVisible(true);
        
        mnu.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnKapatMouseClicked

    private void btnKullaniciSilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKullaniciSilMouseClicked
 
      
        try {
              String deger = tableListe.getValueAt(tableListe.getSelectedRow(), 0).toString();
                System.out.println(deger);
                Silme(Integer.decode(deger));
        } catch (Exception e) {
              JOptionPane.showMessageDialog(null,"Kullanıcı Seçmediniz..", "Hata!",JOptionPane.ERROR_MESSAGE);
        }
      
         
    }//GEN-LAST:event_btnKullaniciSilMouseClicked

    private void btnKullaniciDuzenleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKullaniciDuzenleMouseClicked
       // KULLANICI DUZENLE
       
       
        try {
             String kullanici_id = tableListe.getValueAt(tableListe.getSelectedRow(), 0).toString();
              String kullanici_ismi = tableListe.getValueAt(tableListe.getSelectedRow(), 1).toString();
              String kullanici_sifre = tableListe.getValueAt(tableListe.getSelectedRow(), 2).toString();
              String silme = tableListe.getValueAt(tableListe.getSelectedRow(), 3).toString();
              String duzenleme = tableListe.getValueAt(tableListe.getSelectedRow(), 4).toString();
     
              String admin = tableListe.getValueAt(tableListe.getSelectedRow(), 5).toString();
  
              YonetimDuzenle yntmDuzenle = new YonetimDuzenle(this);
              yntmDuzenle.veriAl(kullanici_ismi,kullanici_sifre,silme,duzenleme,admin,Integer.parseInt(kullanici_id));
              yntmDuzenle.setVisible(true);
              yntmDuzenle.setLocationRelativeTo(null);   
              
                
        } catch (Exception e) {
              JOptionPane.showMessageDialog(null,"Kullanıcı Seçmediniz..", "Hata!",JOptionPane.ERROR_MESSAGE);
              System.err.println("Hata : " + e);
        }
       
    
    }//GEN-LAST:event_btnKullaniciDuzenleMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Menu mnu = new Menu();
        mnu.lblKim.setText(lblKim.getText());
        mnu.setVisible(true);
        mnu.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yonetim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yonetim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yonetim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yonetim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
   
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new Yonetim().setVisible(true);
                   
            }
           
        });
        
  
        
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKapat;
    private javax.swing.JButton btnKullaniciDuzenle;
    private javax.swing.JButton btnKullaniciEkle;
    private javax.swing.JButton btnKullaniciSil;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblKim;
    private javax.swing.JTable tableListe;
    // End of variables declaration//GEN-END:variables

  
}
